"use client";

import { useCallback, useEffect, useMemo, useState } from "react";

type TaskType = "HOUSEKEEPING" | "MAINTENANCE" | "GUEST_REQUEST";
type Thresholds = Record<TaskType, number>;
type Task = { id:string; type:TaskType; status:string; priority:string; title:string; room_code?:string|null; assigned_to_name?:string|null; created_at:string };
type Reservation = { id:string; bookingNumber:string; status:string; checkIn:string; checkOut:string; remainingKgs:number };
type Room = { id:string; code:string; operational_state:"UNKNOWN"|"CLEAN"|"DIRTY"|"IN_INSPECTION"|"TECH_BLOCK" };
type User = { display_name:string; role:string };
type Snapshot = { id:string; createdAt:string; user:string; note:string; activeTaskIds:string[]; escalations:number; activeTasks:number; arrivals:number; departures:number; debtKgs:number|null; dirty:number; inspection:number; tech:number };

const DEFAULTS: Thresholds = { HOUSEKEEPING:45, MAINTENANCE:120, GUEST_REQUEST:30 };
const LABEL: Record<TaskType,string> = { HOUSEKEEPING:"Уборка", MAINTENANCE:"Ремонт", GUEST_REQUEST:"Запрос гостя" };
const ACTIVE = new Set(["OPEN","IN_PROGRESS","IN_INSPECTION"]);
const PRIORITY: Record<string,number> = { URGENT:4, HIGH:3, NORMAL:2, LOW:1 };

function ymd(date = new Date()) { const y=date.getFullYear(); const m=String(date.getMonth()+1).padStart(2,"0"); const d=String(date.getDate()).padStart(2,"0"); return `${y}-${m}-${d}`; }
function addDays(date:Date,n:number){ const x=new Date(date.getFullYear(),date.getMonth(),date.getDate()); x.setDate(x.getDate()+n); return x; }
function ageMin(value:string){ const t=new Date(value).getTime(); return Number.isFinite(t)?Math.max(0,Math.round((Date.now()-t)/60000)):0; }
function ageText(n:number){ return n<60?`${n} мин`:`${Math.floor(n/60)} ч ${n%60?`${n%60} мин`:""}`.trim(); }
function money(n:number){ return new Intl.NumberFormat("ru-RU").format(n); }
function escapeHtml(s:string){ return s.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;"); }

export default function PMSShiftControl(){
  const [tasks,setTasks]=useState<Task[]>([]); const [reservations,setReservations]=useState<Reservation[]>([]); const [rooms,setRooms]=useState<Room[]>([]); const [user,setUser]=useState<User|null>(null);
  const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [tasksComplete,setTasksComplete]=useState(false); const [financeComplete,setFinanceComplete]=useState(false);
  const [thresholds,setThresholds]=useState<Thresholds>(DEFAULTS); const [settingsOpen,setSettingsOpen]=useState(false); const [note,setNote]=useState(""); const [snapshots,setSnapshots]=useState<Snapshot[]>([]); const [acceptedAt,setAcceptedAt]=useState<string|null>(null);
  const today=ymd(); const tomorrow=ymd(addDays(new Date(),1));

  useEffect(()=>{ try{ const a=localStorage.getItem("resort-pms-v7-thresholds"); if(a)setThresholds({...DEFAULTS,...JSON.parse(a)} as Thresholds); const b=localStorage.getItem(`resort-pms-v7-note-${today}`); if(b)setNote(b); const c=localStorage.getItem("resort-pms-v7-snapshots"); if(c)setSnapshots(JSON.parse(c) as Snapshot[]); const d=localStorage.getItem(`resort-pms-v7-accepted-${today}`); if(d)setAcceptedAt(d);}catch{} },[today]);
  useEffect(()=>{ try{localStorage.setItem(`resort-pms-v7-note-${today}`,note)}catch{} },[note,today]);

  const load=useCallback(async()=>{ setLoading(true); setError(null); setTasksComplete(false); setFinanceComplete(false); try{
    const q=new URLSearchParams({start:today,end:tomorrow});
    const [tr,rr,gr,mr]=await Promise.all([fetch("/core/api/v1/ops/tasks?limit=250",{cache:"no-store"}),fetch("/core/api/v1/admin/reception/reservations?limit=500",{cache:"no-store"}),fetch(`/core/api/v1/pms/grid?${q}`,{cache:"no-store"}),fetch("/core/api/v1/auth/me",{cache:"no-store"})]);
    const tb=await tr.json().catch(()=>({})); if(!tr.ok||!Array.isArray(tb.items)) throw new Error("Не удалось получить задачи Resort Core"); const ti=tb.items as Task[]; setTasks(ti); setTasksComplete(ti.length<250);
    const rb=await rr.json().catch(()=>({})); if(rr.ok&&Array.isArray(rb.items)&&typeof rb.complete==="boolean"){ const ri=rb.items as Reservation[]; setReservations(ri); setFinanceComplete(rb.complete===true);} else { setReservations([]); setFinanceComplete(false); }
    const gb=await gr.json().catch(()=>({})); if(!gr.ok||!Array.isArray(gb.rooms)) throw new Error("Не удалось получить номерной фонд"); setRooms(gb.rooms as Room[]);
    if(mr.ok) setUser(await mr.json() as User); else setUser(null);
  }catch(e){setTasks([]);setReservations([]);setRooms([]);setUser(null);setTasksComplete(false);setFinanceComplete(false);setError(e instanceof Error?e.message:"Не удалось загрузить Control Tower")}finally{setLoading(false)} },[today,tomorrow]);
  useEffect(()=>{void load(); const t=window.setInterval(()=>void load(),60000); return()=>window.clearInterval(t)},[load]);

  const sourcesComplete=!loading&&!error&&tasksComplete&&financeComplete;
  const activeTasks=useMemo(()=>tasksComplete?tasks.filter(t=>ACTIVE.has(t.status)):[],[tasks,tasksComplete]);
  const aged=useMemo(()=>activeTasks.map(task=>{const age=ageMin(task.created_at); const threshold=Math.max(5,thresholds[task.type]); const risk=(age/threshold)*10+(PRIORITY[task.priority]||2)*3+(!task.assigned_to_name?4:0); return{task,age,threshold,risk,overdue:age>=threshold}}).sort((a,b)=>b.risk-a.risk),[activeTasks,thresholds]);
  const escalations=useMemo(()=>aged.filter(x=>x.overdue||(!x.task.assigned_to_name&&["URGENT","HIGH"].includes(x.task.priority))),[aged]);
  const arrivals=useMemo(()=>financeComplete?reservations.filter(r=>r.status==="GUARANTEED"&&r.checkIn===today):[],[reservations,today,financeComplete]);
  const departures=useMemo(()=>financeComplete?reservations.filter(r=>r.status==="CHECKED_IN"&&r.checkOut===today):[],[reservations,today,financeComplete]);
  const debt=useMemo(()=>financeComplete?reservations.filter(r=>["GUARANTEED","CHECKED_IN"].includes(r.status)).reduce((s,r)=>s+Math.max(0,r.remainingKgs),0):null,[reservations,financeComplete]);
  const roomMetrics=useMemo(()=>({clean:rooms.filter(r=>r.operational_state==="CLEAN").length,dirty:rooms.filter(r=>r.operational_state==="DIRTY").length,inspection:rooms.filter(r=>r.operational_state==="IN_INSPECTION").length,tech:rooms.filter(r=>r.operational_state==="TECH_BLOCK").length}),[rooms]);
  const previous=snapshots[0]||null; const carried=useMemo(()=>{const current=new Set(activeTasks.map(t=>t.id)); return new Set((previous?.activeTaskIds||[]).filter(id=>current.has(id)))},[previous,activeTasks]);

  function change(type:TaskType,value:number){const next={...thresholds,[type]:Math.max(5,Math.min(1440,value||5))};setThresholds(next);try{localStorage.setItem("resort-pms-v7-thresholds",JSON.stringify(next))}catch{}}
  function requireComplete(){if(sourcesComplete)return true;setError("Handover заблокирован: задачи и reception list должны быть полностью подтверждены Resort Core.");return false}
  function snapshot():Snapshot{return{id:String(Date.now()),createdAt:new Date().toISOString(),user:user?.display_name||"Менеджер",note:note.trim(),activeTaskIds:activeTasks.map(t=>t.id),escalations:escalations.length,activeTasks:activeTasks.length,arrivals:arrivals.length,departures:departures.length,debtKgs:debt,dirty:roomMetrics.dirty,inspection:roomMetrics.inspection,tech:roomMetrics.tech}}
  function save(){if(!requireComplete())return;const next=[snapshot(),...snapshots].slice(0,10);setSnapshots(next);try{localStorage.setItem("resort-pms-v7-snapshots",JSON.stringify(next))}catch{}}
  function accept(){if(!requireComplete())return;const v=new Date().toISOString();setAcceptedAt(v);try{localStorage.setItem(`resort-pms-v7-accepted-${today}`,v)}catch{}}
  function exportJson(){if(!requireComplete())return;const blob=new Blob([JSON.stringify({kind:"three-crowns-shift-handover",version:1,stationLocal:true,snapshot:snapshot(),thresholds,tasksComplete:true,financeComplete:true,escalations:escalations.map(x=>({id:x.task.id,type:x.task.type,room:x.task.room_code,title:x.task.title,assignee:x.task.assigned_to_name,ageMinutes:x.age,controlThresholdMinutes:x.threshold}))},null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`three-crowns-handover-${today}.json`;a.click();URL.revokeObjectURL(url)}
  function print(){if(!requireComplete())return;const s=snapshot();const w=window.open("","_blank","width=960,height=760");if(!w)return;const rows=escalations.slice(0,30).map(x=>`<tr><td>${escapeHtml(x.task.room_code||"—")}</td><td>${escapeHtml(LABEL[x.task.type])}</td><td>${escapeHtml(x.task.title)}</td><td>${escapeHtml(x.task.assigned_to_name||"Не назначен")}</td><td>${escapeHtml(ageText(x.age))} / ${x.threshold} мин</td></tr>`).join("");w.document.write(`<!doctype html><html lang="ru"><head><meta charset="utf-8"><title>Передача смены</title><style>body{font-family:Arial;padding:30px;color:#17263a}.g{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.c{border:1px solid #ddd;padding:12px;border-radius:8px}table{width:100%;border-collapse:collapse;margin-top:20px}td,th{border-bottom:1px solid #ddd;padding:8px;text-align:left;font-size:12px}.n{white-space:pre-wrap;border:1px solid #ddd;padding:12px;border-radius:8px}</style></head><body><h1>Три Короны · Передача смены</h1><p>${escapeHtml(new Date(s.createdAt).toLocaleString("ru-RU"))} · ${escapeHtml(s.user)}</p><div class="g"><div class="c">Заезды<br><b>${s.arrivals}</b></div><div class="c">Выезды<br><b>${s.departures}</b></div><div class="c">Задачи<br><b>${s.activeTasks}</b></div><div class="c">Контроль<br><b>${s.escalations}</b></div><div class="c">DIRTY<br><b>${s.dirty}</b></div><div class="c">Inspection<br><b>${s.inspection}</b></div><div class="c">Tech<br><b>${s.tech}</b></div><div class="c">Остатки<br><b>${s.debtKgs==null?"—":`${money(s.debtKgs)} сом`}</b></div></div><table><thead><tr><th>Номер</th><th>Тип</th><th>Задача</th><th>Ответственный</th><th>Возраст / порог</th></tr></thead><tbody>${rows||"<tr><td colspan='5'>Нет элементов</td></tr>"}</tbody></table><h2>Комментарий смены</h2><div class="n">${escapeHtml(s.note)||"—"}</div><p>Пороги V7 — локальный операционный контроль интерфейса, не backend SLA.</p><script>window.onload=()=>window.print()</script></body></html>`);w.document.close()}

  return <section className="v7-control-tower"><header className="v7-head"><div><p className="eyebrow">Control Tower · V7</p><h2>Передача смены и контроль задач</h2><span>Live задачи, возраст, назначение, фонд и handover-снимок.</span></div><div className="v7-actions"><span className={error?"v7-health bad":sourcesComplete?"v7-health live":"v7-health wait"}>{error?"Core warning":sourcesComplete?"Live source":loading?"Обновление…":"Source incomplete"}</span><button className="btn" onClick={()=>void load()}>↻</button><button className="btn" onClick={()=>setSettingsOpen(v=>!v)}>Пороги</button><button className="btn" onClick={print} disabled={!sourcesComplete}>Печать</button><button className="btn" onClick={exportJson} disabled={!sourcesComplete}>JSON</button></div></header>
  {error&&<div className="v7-warning"><strong>Control Tower</strong><span>{error}</span></div>}{!tasksComplete&&<div className="v7-warning"><strong>Задачи не подтверждены полностью</strong><span>Пока список не доказан полным, task KPI и handover блокируются.</span></div>}{!financeComplete&&<div className="v7-warning"><strong>Reception list не подтверждён полностью</strong><span>V7 требует server `complete=true`; гостевые события, остаток и handover не подменяются нулями.</span></div>}
  {settingsOpen&&<div className="v7-thresholds"><div><strong>Пороги контроля V7</strong><span>Локальная настройка станции, не backend SLA.</span></div>{(["HOUSEKEEPING","MAINTENANCE","GUEST_REQUEST"] as TaskType[]).map(type=><label key={type}>{LABEL[type]} <input type="number" min={5} max={1440} value={thresholds[type]} onChange={e=>change(type,Number(e.target.value))}/> мин</label>)}</div>}
  <div className="v7-kpis"><article className={!tasksComplete?"muted":""}><span>Активные задачи</span><strong>{tasksComplete?activeTasks.length:"—"}</strong><small>{tasksComplete?`${activeTasks.filter(t=>!t.assigned_to_name).length} без ответственного`:"полнота не подтверждена"}</small></article><article className={!tasksComplete?"muted":escalations.length?"danger":"ok"}><span>Требуют контроля</span><strong>{tasksComplete?escalations.length:"—"}</strong><small>{tasksComplete?"возраст / приоритет":"неизвестно"}</small></article><article className={!tasksComplete?"muted":""}><span>Перешли из снимка</span><strong>{tasksComplete?carried.size:"—"}</strong><small>{tasksComplete?(previous?new Date(previous.createdAt).toLocaleString("ru-RU"):"нет прошлого снимка"):"неизвестно"}</small></article><article><span>Номерной фонд</span><strong>{roomMetrics.clean}<small> CLEAN</small></strong><small>{roomMetrics.dirty} dirty · {roomMetrics.inspection} inspection · {roomMetrics.tech} tech</small></article><article className={!financeComplete?"muted":""}><span>Гостевые события</span><strong>{financeComplete?arrivals.length:"—"}<small>{financeComplete?` / ${departures.length}`:""}</small></strong><small>{financeComplete?"заезды / выезды":"не подтверждено"}</small></article><article className={debt==null?"muted":debt>0?"money":"ok"}><span>Остаток активных</span><strong>{debt==null?"—":money(debt)}<small>{debt==null?"":" сом"}</small></strong><small>{financeComplete?"reception read model":"не подтверждено"}</small></article></div>
  <div className="v7-grid"><section className="v7-escalation-card"><div className="v7-section-head"><div><strong>Контроль активных задач</strong><span>Возраст, приоритет и отсутствие назначения.</span></div><b>{tasksComplete?escalations.length:"—"}</b></div><div className="v7-task-list">{!tasksComplete?<p className="v7-empty">Полный список задач не подтверждён.</p>:escalations.length===0?<p className="v7-empty">Нет задач за настроенными порогами.</p>:escalations.slice(0,20).map(x=><article key={x.task.id} className={carried.has(x.task.id)?"carried":""}><div className={`v7-task-type type-${x.task.type.toLowerCase()}`}>{LABEL[x.task.type]}</div><div><strong>{x.task.room_code?`№ ${x.task.room_code} · `:""}{x.task.title}</strong><span>{x.task.assigned_to_name||"Без ответственного"} · {x.task.status} · {x.task.priority}</span></div><div className="v7-age"><strong>{ageText(x.age)}</strong><span>порог {x.threshold} мин</span></div>{carried.has(x.task.id)&&<em>с прошлого снимка</em>}</article>)}</div></section>
  <section className="v7-handover-card"><div className="v7-section-head"><div><strong>Handover</strong><span>Комментарий и воспроизводимый снимок смены.</span></div><b>{snapshots.length}</b></div><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Что должна знать следующая смена: гости, номера, ремонт, оплаты, обещания…" maxLength={4000}/><div className="v7-handover-actions"><button className="primary" onClick={save} disabled={!sourcesComplete}>Сохранить снимок смены</button><button onClick={accept} disabled={!sourcesComplete}>{acceptedAt?"Обновить принятие":"Принять смену"}</button></div><p className="v7-local-disclaimer">Снимки и «принял смену» локальны для рабочей станции и доступны только при полной task + reception выборке; Core-данные не изменяются.</p>{acceptedAt&&<div className="v7-accepted"><strong>Смена принята</strong><span>{new Date(acceptedAt).toLocaleString("ru-RU")} · {user?.display_name||"Менеджер"}</span></div>}<div className="v7-snapshots">{snapshots.slice(0,5).map(s=><article key={s.id}><div><strong>{new Date(s.createdAt).toLocaleString("ru-RU")}</strong><span>{s.user}</span></div><b>{s.escalations} контроль</b><small>{s.activeTasks} задач</small></article>)}{snapshots.length===0&&<p className="v7-empty">Снимков смены ещё нет.</p>}</div></section></div></section>;
}
