"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";

type User={id:string;username:string;display_name:string;role:string;property_code:string};
type MenuItem={id:string;serviceDate:string;mealType:string;name:string;description?:string|null;priceKgs:number;availableQty?:number|null;includedInMealPlan:boolean;active:boolean;sortOrder:number};
type Order={id:string;serviceDate:string;mealType:string;status:string;paymentMode:string;totalKgs:number;notes?:string|null;bookingNumber:string;firstName?:string|null;room_code?:string|null};
const allowedRoles=new Set(["DINING","OWNER","ADMIN","MANAGER"]);
const meals=["BREAKFAST","LUNCH","DINNER"] as const;
function today(){return new Date().toISOString().slice(0,10)}
function money(v:number){return new Intl.NumberFormat("ru-RU").format(v)+" сом"}

export default function DiningConsole(){
 const [user,setUser]=useState<User|null>(null),[checking,setChecking]=useState(true),[username,setUsername]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState("");
 const [date,setDate]=useState(today()),[meal,setMeal]=useState<(typeof meals)[number]>("LUNCH"),[menu,setMenu]=useState<MenuItem[]>([]),[orders,setOrders]=useState<Order[]>([]),[busy,setBusy]=useState(false);
 const [name,setName]=useState(""),[description,setDescription]=useState(""),[price,setPrice]=useState("0"),[qty,setQty]=useState(""),[included,setIncluded]=useState(false);
 useEffect(()=>{fetch("/core/api/v1/auth/me",{cache:"no-store"}).then(async r=>r.ok?await r.json():null).then(v=>setUser(v&&allowedRoles.has(v.role)?v:null)).catch(()=>setUser(null)).finally(()=>setChecking(false));},[]);
 const load=useCallback(async()=>{if(!user)return;setBusy(true);setError("");try{const q=new URLSearchParams({service_date:date,meal_type:meal});const [mr,or]=await Promise.all([fetch(`/core/api/v1/dining/menu?${q}`,{cache:"no-store"}),fetch("/core/api/v1/dining/orders",{cache:"no-store"})]);if(!mr.ok||!or.ok)throw new Error("Не удалось загрузить столовую");setMenu((await mr.json()).items||[]);setOrders((await or.json()).items||[]);}catch(e){setError(e instanceof Error?e.message:"Ошибка")}finally{setBusy(false)}},[user,date,meal]);
 useEffect(()=>{if(user)void load()},[user,load]);
 async function login(e:FormEvent){e.preventDefault();setError("");const r=await fetch("/core/api/v1/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username,password})}).catch(()=>null);const b=r?.ok?await r.json():null;if(!b||!allowedRoles.has(b.role)){setError("Нет доступа к столовой");return}setUser(b);setPassword("")}
 async function logout(){await fetch("/core/api/v1/auth/logout",{method:"POST"}).catch(()=>undefined);setUser(null)}
 async function createItem(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/core/api/v1/dining/menu",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({service_date:date,meal_type:meal,name,description:description||null,price_kgs:Number(price)||0,available_qty:qty===""?null:Number(qty),included_in_meal_plan:included})});if(!r.ok)throw new Error("Не удалось добавить блюдо");setName("");setDescription("");setPrice("0");setQty("");setIncluded(false);await load()}catch(e){setError(e instanceof Error?e.message:"Ошибка")}finally{setBusy(false)}}
 async function patchItem(id:string,patch:any){setBusy(true);try{const r=await fetch(`/core/api/v1/dining/menu/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(patch)});if(!r.ok)throw new Error();await load()}catch{setError("Не удалось изменить блюдо")}finally{setBusy(false)}}
 async function moveOrder(id:string,status:string){setBusy(true);try{const r=await fetch(`/core/api/v1/dining/orders/${id}/status`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});if(!r.ok)throw new Error();await load()}catch{setError("Неверный переход статуса")}finally{setBusy(false)}}
 function next(status:string){return status==="NEW"?"ACCEPTED":status==="ACCEPTED"?"PREPARING":status==="PREPARING"?"READY":status==="READY"?"DELIVERED":null}
 if(checking)return <main className="dining-center"><div className="dining-login">Загрузка…</div></main>;
 if(!user)return <main className="dining-center"><form className="dining-login" onSubmit={login}><p>Три Короны · Staff</p><h1>Столовая</h1><label>Логин<input value={username} onChange={e=>setUsername(e.target.value)} required/></label><label>Пароль<input type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="dining-error">{error}</div>}<button>Войти</button></form></main>;
 return <main className="dining-shell"><header><div><p>Три Короны · Resort OS</p><h1>Столовая</h1><span>{user.display_name} · {user.role}</span></div><button onClick={logout}>Выйти</button></header>{error&&<div className="dining-error">{error}</div>}<section className="dining-controls"><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><div>{meals.map(m=><button key={m} className={meal===m?"active":""} onClick={()=>setMeal(m)}>{m}</button>)}</div><button onClick={load}>Обновить</button></section><div className="dining-columns"><section className="dining-panel"><h2>Меню на день</h2><form className="dining-new" onSubmit={createItem}><input placeholder="Название блюда" value={name} onChange={e=>setName(e.target.value)} required/><textarea placeholder="Короткое описание" value={description} onChange={e=>setDescription(e.target.value)}/><div><input type="number" min="0" placeholder="Цена" value={price} onChange={e=>setPrice(e.target.value)}/><input type="number" min="0" placeholder="Порций (пусто = без лимита)" value={qty} onChange={e=>setQty(e.target.value)}/></div><label><input type="checkbox" checked={included} onChange={e=>setIncluded(e.target.checked)}/> Входит в пакет питания</label><button disabled={busy}>Добавить блюдо</button></form><div className="dining-list">{menu.map(item=><article key={item.id} className={!item.active?"off":""}><div><strong>{item.name}</strong><span>{money(item.priceKgs)} · {item.availableQty==null?"∞":item.availableQty} порций{item.includedInMealPlan?" · пакет":""}</span></div><button onClick={()=>patchItem(item.id,{active:!item.active})}>{item.active?"СТОП":"Вернуть"}</button></article>)}</div></section><section className="dining-panel"><h2>Активные заказы</h2><div className="dining-orders">{orders.length===0&&<p>Нет активных заказов.</p>}{orders.map(o=>{const n=next(o.status);return <article key={o.id}><div><strong>№ {o.room_code||"—"} · {o.firstName||o.bookingNumber}</strong><span>{o.mealType} · {o.status} · {money(o.totalKgs)}</span>{o.notes&&<small>{o.notes}</small>}</div><div>{n&&<button onClick={()=>moveOrder(o.id,n)}>{n}</button>}{["NEW","ACCEPTED"].includes(o.status)&&<button className="danger" onClick={()=>moveOrder(o.id,"CANCELLED")}>Отмена</button>}</div></article>})}</div></section></div></main>
}
